const data = [
  { value: '1', label: 'Allergy and Immunology' },
  { value: '2', label: 'Anesthesiology' },
  { value: '3', label: 'Cardiology' },
  { value: '4', label: 'Cardiothoracic Surgery' },
  { value: '5', label: 'Colon and Rectal Surgery' },
  { value: '6', label: 'Critical Care Medicine' },
  { value: '7', label: 'Dermatology' },
  { value: '8', label: 'Diagnostic Radiology' },
  { value: '9', label: 'Emergency Medicine' },
  { value: '10', label: 'Endocrinology' },
  { value: '11', label: 'Family Medicine' },
  { value: '12', label: 'Gastroenterology' },
  { value: '13', label: 'General Surgery' },
  { value: '14', label: 'Geriatric Medicine' },
  { value: '15', label: 'Gynecologic Oncology' },
  { value: '16', label: 'Hematology' },
  { value: '17', label: 'Hospice and Palliative Medicine' },
  { value: '18', label: 'Hospitalist Medicine' },
  { value: '19', label: 'Infectious Disease' },
  { value: '20', label: 'Internal Medicine' },
  { value: '21', label: 'Interventional Cardiology' },
  { value: '22', label: 'Interventional Radiology' },
  { value: '23', label: 'Medical Genetics' },
  { value: '24', label: 'Medical Oncology' },
  { value: '25', label: 'Neonatal-Perinatal Medicine' },
  { value: '26', label: 'Nephrology' },
  { value: '27', label: 'Neurology' },
  { value: '28', label: 'Neurosurgery' },
  { value: '29', label: 'Nuclear Medicine' },
  { value: '30', label: 'Obstetrics and Gynecology' },
  { value: '31', label: 'Occupational Medicine' },
  { value: '32', label: 'Ophthalmology' },
  { value: '33', label: 'Oral and Maxillofacial Surgery' },
  { value: '34', label: 'Orthopedic Surgery' },
  { value: '35', label: 'Otolaryngology (ENT)' },
  { value: '36', label: 'Pain Medicine' },
  { value: '37', label: 'Pathology' },
  { value: '38', label: 'Pediatric Cardiology' },
  { value: '39', label: 'Pediatric Endocrinology' },
  { value: '40', label: 'Pediatric Gastroenterology' },
  { value: '41', label: 'Pediatric Hematology-Oncology' },
  { value: '42', label: 'Pediatric Infectious Disease' },
  { value: '43', label: 'Pediatric Nephrology' },
  { value: '44', label: 'Pediatric Neurology' },
  { value: '45', label: 'Pediatric Pulmonology' },
  { value: '46', label: 'Pediatric Rheumatology' },
  { value: '47', label: 'Pediatrics' },
  { value: '48', label: 'Physical Medicine and Rehabilitation' },
  { value: '49', label: 'Plastic Surgery' },
  { value: '50', label: 'Preventive Medicine' },
  { value: '51', label: 'Psychiatry' },
  { value: '52', label: 'Pulmonology' },
  { value: '53', label: 'Radiation Oncology' },
  { value: '54', label: 'Reproductive Endocrinology' },
  { value: '55', label: 'Rheumatology' },
  { value: '56', label: 'Sleep Medicine' },
  { value: '57', label: 'Spinal Surgery' },
  { value: '58', label: 'Sports Medicine' },
  { value: '59', label: 'Surgical Oncology' },
  { value: '60', label: 'Thoracic Surgery' },
  { value: '61', label: 'Transplant Surgery' },
  { value: '62', label: 'Trauma Surgery' },
  { value: '63', label: 'Urgent Care Medicine' },
  { value: '64', label: 'Urogynecology' },
  { value: '65', label: 'Urology' },
  { value: '66', label: 'Vascular Surgery' },
  { value: '67', label: 'Adolescent Medicine' },
  { value: '68', label: 'Clinical Pharmacology' },
  { value: '69', label: 'Medical Toxicology' },
  { value: '70', label: 'Forensic Pathology' },
  { value: '71', label: 'Public Health and General Preventive Medicine' },
  { value: '72', label: 'Undersea and Hyperbaric Medicine' },
  { value: '73', label: 'Addiction Medicine' },
  { value: '74', label: 'Pain Management' },
  { value: '75', label: 'Military Medicine' },
  { value: '76', label: 'Hyperbaric Medicine' },
  { value: '77', label: 'Pediatric Surgery' },
  { value: '78', label: 'Emergency Ultrasound' },
  { value: '79', label: 'Neurodevelopmental Disabilities' },
  { value: '80', label: 'Clinical Neurophysiology' },
  { value: '81', label: 'Gynecology' },
  { value: '82', label: 'Cardiac Electrophysiology' },
  { value: '83', label: 'Pediatric Anesthesiology' },
  { value: '84', label: 'Neurocritical Care' },
  { value: '85', label: 'Radiologic Physics' },
  { value: '86', label: 'Interventional Neuroradiology' },
  { value: '87', label: 'Maternal-Fetal Medicine' },
  { value: '88', label: 'Clinical Informatics' },
  { value: '89', label: 'Geriatric Psychiatry' },
  { value: '90', label: 'Medical Microbiology' },
  { value: '91', label: 'Cytopathology' },
  { value: '92', label: 'Dermatopathology' },
  { value: '93', label: 'Chemical Pathology' },
  { value: '94', label: 'Blood Banking/Transfusion Medicine' },
  { value: '95', label: 'Anatomic Pathology' },
  { value: '96', label: 'Clinical Pathology' },
  { value: '97', label: 'Medical Biochemical Genetics' },
  { value: '98', label: 'Molecular Genetic Pathology' },
  { value: '99', label: 'Osteopathic Manipulative Medicine' },
  { value: '100', label: 'Telemedicine' },
];

export { data };
